name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  PATH_FOR_LINT: "src config tests"
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  DEPLOY_PATH: "/home/${{ secrets.SERVER_USER }}/otus-cicd"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          source .bashrc
          pip install --upgrade pip
          pip install -r requirements/requirements-lint.txt
          pip install -r requirements/requirements.txt

      - name: Run isort
        run: isort ${PATH_FOR_LINT} --check --profile black

      - name: Run black
        run: black ${PATH_FOR_LINT} --check

      - name: Run ruff
        run: ruff check ${PATH_FOR_LINT}

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          source .bashrc
          pip install --upgrade pip
          pip install -r requirements/requirements-test.txt
          pip install -r requirements/requirements.txt

      - name: Run pytest
        run: |
          source .bashrc
          pytest --cov=src tests